services:
  - type: web
    name: bookyourshow-server
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 4000
      - key: MONGO_URI
        sync: false
      - key: API_READ_ACCESS_TOKEN
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
